# Generated by Django 5.2 on 2025-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
