# Generated by Django 5.2 on 2025-04-12 13:37

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_bio_appuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to=accounts.models.user_profile_picture_path)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
